### ISSUE TITLE
Blending modes

### ISSUE THREAD

**Issue by remylagerweij** [sarcadass/granim.js#10]
This is not a issue but a feature request.

Is an implementation of blending modes for gradients coming up? It would be really nice to be able to toggle these in combination with images laying underneath.

**Comment by sarcadass** [comment]
I don't really understand what you mean by "blending modes".
Can you be more specific please?

**Comment by remylagerweij** [comment]
Blending modes are ways of blending the one layer over the other in canvas resulting in a different see-through effect.

It is achieved by making use of the `globalCompositeOperation` property

[Mozilla Developer API](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation)
[Basic Adobe Tutorial](http://blogs.adobe.com/webplatform/2014/02/24/using-blend-modes-in-html-canvas/)

**Comment by sarcadass** [comment]
It's a good idea !
I see what I can do and keep you posted in this issue.

**Comment by pranaygp** [comment]
@remylagerweij would you like to work on this and make a PR with your solution. If not, we'll add it to our backlog and work on this after some cleanup.

**Comment by sarcadass** [comment]
@pranaygp @remylagerweij, I already started to work on this.
The implementation of the color blending modes is pretty easy but I have to add an image alignment option (strech, center, poster) and make it work for the reponsive, in other words, reproduce the CSS behavior because the image will have to be drawn directly in the canvas and won't be a DOM element you can manipulate with CSS anymore.

**Comment by sarcadass** [comment]
This feature has been added in the last version released.
