### ISSUE TITLE
Browser Support

### ISSUE THREAD

**Issue by michaelzoidl** [sarcadass/granim.js#18]
Hey sarcadass,
awesome lib, but one question - what browsers are supported? (is it pure canvas? By default canvas supports >=IE9)

**Comment by pranaygp** [comment]
@michaelzoidl Here's a support chart for the canvas element: https://en.wikipedia.org/wiki/Canvas_element#Browser_support

However, some of our JS is also not compatible with older browsers:
https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector#Browser_Compatibility

This second issue is easily fixable if you use a polyfill for older browsers.

Let me know if there is a specific issue you're having trouble with.

For now, I'm gonna go ahead and close this issue since it doesn't require action on our end (afaik).
