### ISSUE TITLE
bower.json

### ISSUE THREAD

**Issue by muuvmuuv** [sarcadass/granim.js#21]
Hey, could you add a bower.json file. Im mostly using bower in my projects for dependencies.

Thank you! Great script.

**Comment by pranaygp** [comment]
@sarcadass I don't think we should support bower. I know a lot of projects are moving away from it and towards npm since npm can also handle browser dependencies, and webpack/browserify only further improves that support. However, if you want bower support, I can work on getting that set up. We'll have to maintain our bower package as well if we do this.

**Comment by sarcadass** [comment]
@pranaygp It's true that supporting Bower is redundant if we already support NPM.
I know that a lot of people are still using Bower, so it could be great to also support it.
We'll just have to bump the version in the `bower.json` for each new release.
I assign you the issue.

**Comment by pranaygp** [comment]
:+1:

**Comment by pranaygp** [comment]
Bower support added and module registered in 4980161
