### ISSUE TITLE
Trigger initialization

### ISSUE THREAD

**Issue by SebaGnich** [sarcadass/granim.js#33]
Hello,

I would like to use the gradients in multiple "tiles". It works so far, I can initialize them individually (eg. onClick change state).

But most of the tiles are not visible at the beginning (display: none), so when I initialize them, the scripts says they're 0 height an width. Only if I resize the window it recreates them and the gradient is visible. 

Is it possible to trigger it? 

Thank you!

**Comment by sarcadass** [comment]
Can you please reproduce this bug on codepen or jsfiddle? It will be easier to debug.

**Comment by SebaGnich** [comment]
So here is the pen:
https://codepen.io/SebaGnich/pen/BwMZar

When you toggle, you see it has no gradient. To show that it works, you need to remove the `display: none;`.

**Comment by sarcadass** [comment]
The script needs to set the `width` and `height` attributes on the `<canvas>` by getting this info from the DOM. In this case, because the canvas element is not displayed these values are 0.

A simple solution would be to create the Granim instance when the element is supposed to be displayed, I created a pen that shows how:
https://codepen.io/sarcadass/pen/BwbxRE
