### ISSUE TITLE
CPU Usage

### ISSUE THREAD

**Issue by oyeanuj** [sarcadass/granim.js#6]
Hi @sarcadass!  The gradient-animator looks great, thank you for open sourcing this! Wondering if you see it using too much CPU as well when you use them?

**Comment by sarcadass** [comment]
The gradient have to recalculate the colors on each frame, so it have to use some CPU.
Also the bigger the canvas, the bigger it will use GPU.
The animation is based around `requestAnimationFrame()` so it will pause the function when you change tab. You also have an option `options.isPausedWhenNotInView` to pause the function when it's not in window view (or to start it only when it's in view).

I can achieve 60fps with a 1920*1080 resolution on my computer (see the picture).
![granim-issue-6](https://cloud.githubusercontent.com/assets/2452603/18258144/b53407c4-73d0-11e6-9fc4-f0e6e0989c29.png)

Is the animation fluid on your computer or do you have problems running it smoothly?

**Comment by gkostyanikov** [comment]
Hi, i have to confirm intensive cpu usage on stable and canary channel in chrome. Same example in firefox stable works pretty smooth. osx el captain btw.
![image](https://cloud.githubusercontent.com/assets/666122/18393120/ec07258a-76bc-11e6-89cf-b090ed3768c6.png)

**Comment by sarcadass** [comment]
I will investigate to detect bottlenecks and try to reduce the CPU footprint.

**Comment by sarcadass** [comment]
I figured out why it was so intensive on Chrome (correct usage on Firefox and ie11).
Chrome had to enlarge the gradients to fill the canvas, because the size was not set correctly.

**Chrome before the fix:**
![6-chrome-before](https://cloud.githubusercontent.com/assets/2452603/18449836/08a1f80c-7931-11e6-8cc9-b8c2a5b72318.png)

**Chrome after the fix:**
![6-chrome-after](https://cloud.githubusercontent.com/assets/2452603/18449861/1b0b4ba6-7931-11e6-95c6-ebff376f1585.png)

@gkostyanikov can you confirm ?

**Comment by gkostyanikov** [comment]
@sarcadass yes, thank you, much better now!

**Comment by sarcadass** [comment]
Nice, I close the ticket now.
